### ISSUE TITLE
:lipstick: UI 깨지는 부분들 수정

### ISSUE THREAD

**Issue by yoojin-park19** [yoojin-park19/Button#58]
테스트 화면이 계속 깨집니다. 
컴퓨터 화면에서는 각 항목이 너무 작고, 모바일에서는 wrap부분이 깨집니다.

**Comment by Sangdon1029** [comment]
# TEST PAGE ERRORS
## 1. Test Pages (글자가 밀리는 현상)
<p align="center">
<img width="300" alt="글자가 밀리는 현상" src="https://user-images.githubusercontent.com/93380732/163954044-59838622-c083-473c-bae3-08ff0635c054.png">
</p>

## 2. Test Pages (Wrap밖으로 Item이 밀리는 현상)
<p align="center">
<img width="300" alt="Wrap밖으로 Item이 밀리는 현상" src="https://user-images.githubusercontent.com/93380732/163954113-f74f7a1a-c62a-4039-8ea6-8a2f83ba7d73.png">
</p>
